name: Course Task
description: Template for course assignments and tasks
title: "[Course task]: "
labels: ["course-task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the course task.
    validations:
      required: true
      
  - type: textarea
    id: expected-evidence
    attributes:
      label: Expected Evidence or Deliverable
      description: List the expected outputs.
    validations:
      required: true
